### PR TITLE
Bsekisser master core flat inst d5r5 patch3

### PR DESCRIPTION
**Pull request by bsekisser**

### CODE REVIEW

**Comment by bsekisser** [comment]
@buserror

I essentially pulled most of the changes all the way back to where they started...  let me know if this looks good or that I went too far.

**Comment by buserror** [comment]
So how is this different from your 'core-2' branch? I'll have a look at this one tonight anyway, thanks! Does it pass all the tests etc so far?

**Comment by bsekisser** [comment]
The core-2 branch has everything (including this)...  follow that.  It was at this point I made some big changes where things occurred at different stages as opposed to before.  The changes made in this branch took out some of the apparent thought process that occurred and was more readily visible in the previous set.  The question I had to myself was, did I take that too far?.

**Comment by bsekisser** [comment]
Most times I run four tests...  make...  instrtest.elf...  instrtiming.elf...  and the fignition code that has some rudimentary performance counters.  I run those after almost every single instruction converted.  I have yet to run the other tests (this time around) that the simavr project has but your bringing it up has me thinging it would not hurt checking.

**Pull request closed without merging**
